apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret
type: Opaque
data:
  # Base64 encoded: elastic
  elastic-user: ZWxhc3RpYw==
  # Base64 encoded: changeme
  elastic-password: Y2hhbmdlbWU=
  # NOTE: These credentials are not used if xpack.security.enabled is false in elasticsearch.yml
