apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: iot-kafka-wifi-loss-2pct
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: iot-producer
  target:
    mode: all
    selector:
      namespaces:
        - default
      labelSelectors:
        app: kafka
  direction: both
  loss:
    loss: "4"